-- DDL para o Migration Flyway com Herança JOINED

-- 1. Tabela PESSOA (Tabela Raiz da Herança)
-- Contém todos os campos comuns (id, nome e endereço embutido)
CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    rua VARCHAR(255),
    numero VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    cep VARCHAR(255),
    -- Coluna opcional, mas recomendada para otimizar consultas na tabela pai
    tipo_pessoa VARCHAR(31) NOT NULL,
    CONSTRAINT pk_pessoa PRIMARY KEY (id)
);

-- 2. Tabela CLIENTE_PF (Subclasse)
-- Contém apenas os campos próprios (cpf) e a chave primária herdada (id)
CREATE TABLE cliente_pf (
    id BIGINT NOT NULL,
    cpf VARCHAR(255),
    CONSTRAINT pk_clientepf PRIMARY KEY (id)
);
ALTER TABLE cliente_pf ADD CONSTRAINT FK_CLIENTEPF_ON_ID FOREIGN KEY (id) REFERENCES pessoa (id);

-- 3. Tabela PROFISSIONAL (Subclasse)
-- Contém apenas os campos próprios (cnpj, classificacao, etc.)
CREATE TABLE profissional (
    id BIGINT NOT NULL,
    cnpj VARCHAR(255),
    classificacao VARCHAR(255),
    especialidade VARCHAR(255),
    CONSTRAINT pk_profissional PRIMARY KEY (id)
);
ALTER TABLE profissional ADD CONSTRAINT FK_PROFISSIONAL_ON_ID FOREIGN KEY (id) REFERENCES pessoa (id);

-- 4. Tabela SERVICO
CREATE TABLE servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_servico VARCHAR(255),
    descricao_servico VARCHAR(255),
    CONSTRAINT pk_servico PRIMARY KEY (id)
);

-- 5. Tabela AVALIA
CREATE TABLE avalia (
    avalia_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comentario VARCHAR(255),
    nota DOUBLE PRECISION NOT NULL,
    data_avaliacao DATE,
    CONSTRAINT pk_avalia PRIMARY KEY (avalia_id)
);

-- 6. Tabela TELEFONE (Corrigido para ter ID próprio)
CREATE TABLE telefone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_pessoa BIGINT,
    telefone VARCHAR(255),
    CONSTRAINT pk_telefone PRIMARY KEY (id)
);
ALTER TABLE telefone ADD CONSTRAINT FK_TELEFONE_ON_ID_PESSOA FOREIGN KEY (id_pessoa) REFERENCES pessoa (id);

-- 7. Tabela ESPECIALIDADE (Corrigido para ter ID próprio e FK para Profissional)
CREATE TABLE especialidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_profissional BIGINT,
    especialidade VARCHAR(255),
    CONSTRAINT pk_especialidade PRIMARY KEY (id)
);
ALTER TABLE especialidade ADD CONSTRAINT FK_ESPECIALIDADE_ON_ID_PROFISSIONAL FOREIGN KEY (id_profissional) REFERENCES profissional (id);

-- 8. Tabela CONTRATA (Tabela de Relacionamento)
CREATE TABLE contrata (
    contrata_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    data_hora TIMESTAMP WITHOUT TIME ZONE,
    forma_pagamento VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    id_cliente BIGINT,
    id_profissional BIGINT,
    id_servico BIGINT,
    id_avalia BIGINT,
    CONSTRAINT pk_contrata PRIMARY KEY (contrata_id)
);

-- Chaves Estrangeiras da Tabela CONTRATA
ALTER TABLE contrata ADD CONSTRAINT FK_CONTRATA_ON_ID_CLIENTE FOREIGN KEY (id_cliente) REFERENCES cliente_pf (id);
ALTER TABLE contrata ADD CONSTRAINT FK_CONTRATA_ON_ID_PROFISSIONAL FOREIGN KEY (id_profissional) REFERENCES profissional (id);
ALTER TABLE contrata ADD CONSTRAINT FK_CONTRATA_ON_ID_SERVICO FOREIGN KEY (id_servico) REFERENCES servico (id);
ALTER TABLE contrata ADD CONSTRAINT FK_CONTRATA_ON_ID_AVALIA FOREIGN KEY (id_avalia) REFERENCES avalia (avalia_id);
ALTER TABLE contrata ADD CONSTRAINT UK_CONTRATA_ID_AVALIA UNIQUE (id_avalia); -- Garante 1 contrato para 1 avaliação